version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:41666"
    volumes:
      - ./main_service/:/code/
    command: [ "python", "manage.py", "runserver", "0.0.0.0:41666" ]
