version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:41666"
    volumes:
      - ./main_service/:/code/
      - ./entrypoint.dev.sh:/code/entrypoint.dev.sh
    entrypoint: bash entrypoint.dev.sh
